### ISSUE TITLE
Relation "cubedash.product" does not exist

### ISSUE THREAD

**Issue by DeZhao-Zhang** [opendatacube/datacube-explorer#120]
1. While i visit the web, the server give the wrong of
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "cubedash.product" does not exist
LINE 2: FROM cubedash.product 
             ^

[SQL: SELECT cubedash.product.dataset_count, cubedash.product.time_earliest, cubedash.product.time_latest, now() - cubedash.product.last_refresh AS last_refresh_age, cubedash.product.id AS id_, cubedash.product.
```
2. the datacube is ok, while i check 

![image](https://user-images.githubusercontent.com/21255807/79176387-adf1f000-7e32-11ea-98dc-9e5d66877eba.png)

3. datacube-explore is also run ok

![image](https://user-images.githubusercontent.com/21255807/79176517-0923e280-7e33-11ea-92cc-ebbdb11dacd0.png)

4. I do not see any config about the database in datacube-explorer, Did I miss something

**Comment by jeremyh** [comment]
Hello, thanks for the report.

Did you run `cubedash-gen`? It usually creates those tables

See here:  https://github.com/opendatacube/datacube-explorer#summary-generation

(I’m surprised, though, because I thought the error message was better than that if you haven’t run the init command yet...)

> I do not see any config about the database in datacube-explorer, Did I miss something

It uses your existing datacube config. 

`cubedash-gen --init` creates a separate schema for Explorer in the existing datacube database.

**Comment by DeZhao-Zhang** [comment]
It works, thanks very much. 
1. It was beacase I do not have postgis extension, but while I run `nohup cubedash-gen --init --all &>> summary-gen.log &`, there was no wrong message.
2. while i use `cubedash-gen --init`, it gives me wrong message, may be it can be added in readme for user to test environment.

Thanks!
