### ISSUE TITLE
Remove logging passwords to console in cubedash-gen 

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#126]
Cubedash-Gen writes passwords to log , mask these.

**Comment by jeremyh** [comment]
Nice catch.

`cubedash-gen` doesn’t deal with any passwords directly, but is logging the `str()` of datacube’s LocalConfig. I wonder if we should push this upstream; should LocalConfig be printing passwords as part `__str__()` and `__repr__()`? It _is_ useful to log what datacube we’re connecting to.

We never hit this previously because we never put passwords in LocalConfig before: `.pgpass`  has always been preferred for local password storage.

**Comment by whatnick** [comment]
In kubernetes based deployments the password comes in from environments (passing via files is not encouraged - stateless deployments and all) . Datacube can accept via a DB_URI in sqlalchemy style or 5 or so scattered ENV variables. Please tag the relevant **__repr__** or **__str__** line in datacube for this.

**Comment by jeremyh** [comment]
Relevant code:

https://github.com/opendatacube/datacube-core/blob/610ee9758978f332c6a5f587c34234e3926b479d/datacube/config.py#L144-L152

**Comment by jeremyh** [comment]
And in Explorer:

https://github.com/opendatacube/datacube-explorer/blob/ea57fb18a94c9a5b7c7cd9ac4a0f7b092c761fd4/cubedash/generate.py#L72-L74

**Comment by whatnick** [comment]
This has been fixed in datacube-core and should be fixed in container builds. Creating new issue to upgrade explorer container to now released datacube-core 1.8.0.
