### ISSUE TITLE
Determine Extents of a Product

### ISSUE THREAD

**Issue by clausmichele** [opendatacube/datacube-explorer#195]
Continuing from here https://github.com/opendatacube/datacube-core/issues/366
Is it possible to get the extent of the products with datacube-explorer, without using the web interface? Where do I find the files used by datacube-explorer with this information? How to update them when I add new datasets?

Thanks in advance for the support

**Comment by jeremyh** [comment]
There technically are ways to do it, though we haven't officially made these public.

The most stable api is to use the front-end REST endpoints, which will return it as a geojson. Explorer's own interface uses these addresses.

Add `/api` before any of these URLs:
https://github.com/opendatacube/datacube-explorer/blob/f8a1b9ed9f533fbbbc42e55c6ce0975682cb35ae/cubedash/_api.py#L56-L59

For example,
- A full product footprint: https://explorer.dea.ga.gov.au/api/footprint/ls5_fc_albers
- Just the product in year 2011: https://explorer.dea.ga.gov.au/api/footprint/ls5_fc_albers/2011

(these geojson addresses can, of course, be read and parsed from Python libraries)

---

The less-stable way is to use the internal Python functions. These are less stable because we will probably change them in future releases as Explorer's own interface changes.

```python
    from datacube import Datacube
    from cubedash.summary import SummaryStore

    # The types returned, just for clarity.
    from cubedash.summary import TimePeriodOverview
    from shapely.geometry import MultiPolygon

    # Get a datacube as per normal.
    with Datacube(app='explorer-test') as dc:

        # Initialise your Explorer summary store using a datacube index
        store = SummaryStore.create(dc.index)
        
        # Get the overview for a product (can also give it year, month, day to drill down)
        time_period_overview : TimePeriodOverview = store.get(product_name='ls5_fc_albers')
        # Get a footprint in shapely format.
        footprint: MultiPolygon = time_period_overview.footprint_wgs84
        # ... there are other useful properties. See TimePeriodOverview.
        dataset_count : int = time_period_overview.dataset_count
        # .... etc
```


To update these footprints, you can use `cubedash-gen` command as mentioned in the main docs, or call the update/refresh functions directly on your `SummaryStore` (.... which are again, not necessarily a stable api).

**Comment by clausmichele** [comment]
Both suggestion works. It would be nice to add to the api the return of a datacube extent as STAC standard https://stacspec.org/STAC-api.html#operation/getCollections

**Comment by jeremyh** [comment]
Good to hear! We do actually have that too, if you only need a bbox+interval and not the full geometry.

URL `/stac` gives a list of collections, and you can get individual ones by following the links.

Example: 
- Collections: https://explorer.dea.ga.gov.au/stac 
- and a single collection with bbox/interval: https://explorer.dea.ga.gov.au/collections/ls8_nbar_scene

This is being vastly improved in #202 (which brings it up to the newer stac standard, and adds/fixes the remaining urls for stac-api).

**Comment by clausmichele** [comment]
wow nice! I didn't know about this. Do you also know if #202 makes also band names available in the single collections?

**Comment by omad** [comment]
The original question seems to be resolves, so I'm going to close this. If your question still needs answering can you please open as a new ticket.
