### ISSUE TITLE
STAC API doesn't have Assets for some products

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#227]
For example, `ga_ls_wo_3` doesn't have assets: https://explorer.dev.dea.ga.gov.au/stac/collections/ga_ls_wo_3/items

Also, `ga_ls8c_ard_3` doesn't have assets: https://explorer.dev.dea.ga.gov.au/stac/collections/ga_ls8c_ard_3/items

Note that assets need to have `proj` fields to be able to be indexed easily into the ODC:

```
"B03": {
"title": "Band 3 (green)",
"type": "image/tiff; application=geotiff; profile=cloud-optimized",
"roles": [
"data"
],
"gsd": 10,
"eo:bands": [
{
"name": "B03",
"common_name": "green",
"center_wavelength": 0.56,
"full_width_half_max": 0.045
}
],
"href": "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/18/T/UM/2020/11/S2A_18TUM_20201116_0_L2A/B03.tif",
"proj:shape": [
10980,
10980
],
"proj:transform": [
10,
0,
300000,
0,
-10,
4700040,
0,
0,
1
]
},
```

**Comment by jeremyh** [comment]
They are currently excluded by default unless you set `STAC_DEFAULT_FULL_ITEM_INFORMATION = True` in the deployment config (see [doc](https://github.com/opendatacube/datacube-explorer#how-can-i-configure-the-deployment) and [pr description](https://github.com/opendatacube/datacube-explorer/pull/202)) 

... or individually by adding `&_full=true` to the query URL, eg: `https://explorer.dev.dea.ga.gov.au/stac/collections/ga_ls_wo_3/items?_full=true`

It's turned off by default in the current release because the "full information" requires going to ODC tables (instead of just Explorer tables), which are extremely slow in the current implementation, especially with paging, and cause timeouts in too many searches in our cloud deployment.

.... but the full asset details are always accessible if you follow the url for each search result, eg: https://explorer.dev.dea.ga.gov.au/stac/collections/ga_ls_wo_3/items/03feb8ce-b371-5b4f-9097-90c9e4051ea5

It's not ideal...  but timeouts mean that no one can fetch anything. For now it's opt-in to a slower api.
