### ISSUE TITLE
Investigate `stac_validator`'s mismatch with Explorer

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#257]
https://github.com/sparkgeo/stac-validator
```
(base) ubuntu@:~$ stac_validator https://explorer.dev.dea.ga.gov.au/stac/collections/aster_aloh_group_composition
[
    {
        "path": "https://explorer.dev.dea.ga.gov.au/stac/collections/aster_aloh_group_composition",
        "asset_type": "collection",
        "id": "aster_aloh_group_composition",
        "validated_version": "1.0.0-beta.2",
        "valid_stac": false,
        "error_type": "ValidationError",
        "error_message": "None is not of type 'string'. Error is in license"
    }
]
(base) ubuntu@:~$ stac_validator https://explorer.dev.dea.ga.gov.au/stac
[
    {
        "path": "https://explorer.dev.dea.ga.gov.au/stac",
        "asset_type": "catalog",
        "id": "AWS_EKS_Dev_Explorer",
        "validated_version": "1.0.0-beta.2",
        "valid_stac": true
    }
]
(base) ubuntu@:~$ stac_validator https://explorer.dev.dea.ga.gov.au/stac/collections/aster_feoh_group_content/items
[
    {
        "path": "https://explorer.dev.dea.ga.gov.au/stac/collections/aster_feoh_group_content/items",
        "asset_type": "catalog",
        "valid_stac": false,
        "error_type": "KeyError",
        "error_message": "Key Error: 'id'"
    }
]
```

**Comment by jeremyh** [comment]
(Copied from Slack for visibility)

Thanks for the report!

Those two errors are because:

- The `license` field is mandatory in Stac, but those DEA products don't have a license specified. Explorer will include the license in Stac when it sees one (a default license can be added to Explorer's config).
- `stac_validator` is validating `/items` as a Stac Catalog, instead of as a Stac FeatureCollection. Last I tried I got the same error for other public  stac-api endpoints, not just for Explorer. My memory is fuzzy, but I believe the answer at the time was that it was written for validating static catalogs, not dynamic. (I'll need to look this up?)

Note that Explorer's own integration tests do the same thing as the `stac_validator` tool: they both validate the stac results against the stac standard's jsonschemas. But our tests handle the above two points too.

We should definitely make it more visible to people that they have ODC fields missing that are required for Stac. Or short term, at least add it to the FAQ.
