### ISSUE TITLE
Expand our tests with more Stac-API use-cases

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#258]
```

1. Searches using STAC specification (search)
 
# Using POST/HTTP
 curl --header "Content-Type: application/json"  \
     --request POST \
     --data '{"collections":"ga_s2_gm","datetime":"2019-01-01/2019-01-01"}' \
     https://explorer.digitalearth.africa/stac/search >> output.json
 
# Using GET/HTTP 
 curl --header "Content-Type: application/json" \
     --request GET "https://explorer.digitalearth.africa/stac/search?collections=ga_s2_gm&     datetime=2019-01-01/2019-01-01" >> output.json

2. Searches using the WFS3 standard (collection path)
 
curl --header "Content-Type: application/json" \
     --request GET "https://explorer.digitalearth.africa/collections/ga_s2_gm/items?datetime=2000-01-01/2000-01-01&bbox=-48.206,-14.195,-45.067,-12.272" >> output.json
```
![image](https://user-images.githubusercontent.com/24644475/105949367-b0bb8a00-60c0-11eb-9c96-44436a8d6cc0.png)

![image](https://user-images.githubusercontent.com/24644475/105949375-b4e7a780-60c0-11eb-80e2-3d68cf270c41.png)

![image](https://user-images.githubusercontent.com/24644475/105949393-b913c500-60c0-11eb-9d38-051ed03a45fe.png)

**Comment by jeremyh** [comment]
Those results are because it's querying with a newer version of Stac-Api than Explorer supported at the time. For instance, older versions of the standard used the name `time` for filtering instead of `datetime`, and unknown filters are ignored.

We improved support for the newer Stac-Api in [release 2.4](https://github.com/opendatacube/datacube-explorer/releases), so those parameters should hopefully work now (?)

**Comment by omad** [comment]
As commented, this is probably fixed and can be reopened if it shows up again.
