### ISSUE TITLE
Curious Appearance of Dataset Boundaries

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#336]
Hi Jeremy,

@GypsyBojangles and I are wondering what's up with the doubled outlines  [on this page of LS8 ARD](https://explorer.prod.dea.ga.gov.au/products/ga_ls8c_ard_3/extents/2021/6/5).

Do you know what's going on?

![image](https://user-images.githubusercontent.com/108979/140201443-1562d194-0be3-4e54-867e-60947fd401a6.png)

**Comment by jeremyh** [comment]
Yep! This is because Landsat 8 wasn't completely in position when the first observations were taken for those path/rows. And the "region" polygon shown is a union of all datasets that claim to be in that region.

[First observation](https://explorer.prod.dea.ga.gov.au/products/ga_ls8c_ard_3/datasets/6b075b96-8b5e-46b5-8285-0a3af8e7d425) (slightly to the left,.. but still categorised as 105 076 by USGS): 
![Screenshot from 2021-11-04 10-21-41](https://user-images.githubusercontent.com/25688/140232242-f7bc5851-f773-45e3-a2ed-960f2e1f02d5.png)


[Latter one](https://explorer.prod.dea.ga.gov.au/products/ga_ls8c_ard_3/datasets/4bc39ec4-521f-41b2-9aac-ec844c0f6acb) in the final position:
![Screenshot from 2021-11-04 10-21-36](https://user-images.githubusercontent.com/25688/140232252-b2876bf5-fe6e-4279-af76-5d61aab24216.png)

And [the region](https://explorer.prod.dea.ga.gov.au/product/ga_ls8c_ard_3/regions/105076) polygon is a union of everything that says "105 076":

![Screenshot from 2021-11-04 10-23-31](https://user-images.githubusercontent.com/25688/140232392-96b1a5f8-7996-4973-b75b-8eb581b1e424.png)

You can click "datasets" in the top right to view the actual dataset polygons for that day, which is probably what you're expecting to see.

.... it's a little weird, admittedly, to default to region polygons on a single day like this when it's a scene-based product.

But regions were often a lot cleaner to display than individual polys (which sometimes had multiple unclickable overlaps etc) and we often couldn't display all of them due to their high count on some days. But maybe that decision is a little more questionable now that we don't ingest products and they more closely follow scenes.

**Comment by omad** [comment]
Thank you for the explanation!

That makes sense, it looks a little funny, but, not terribly so.

I'd never noticed the Dataset/Region toggle either.
