### ISSUE TITLE
Inconsistent views of month vs day datasets

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#41]
We've been using the [DEA deployment of dashboard](https://data.dea.gadevs.ga/) to keep track recently processed data. There's a bug where some pages are stuck displaying out of date data.

https://data.dea.gadevs.ga/ls8_fc_albers/2018/10
![screen shot 2018-11-01 at 10 56 08 am](https://user-images.githubusercontent.com/108979/47825268-137c2900-ddc5-11e8-846c-cf32fe1a2b49.png)

vs
https://data.dea.gadevs.ga/ls8_fc_albers/2018/10/5
![screen shot 2018-11-01 at 10 58 11 am](https://user-images.githubusercontent.com/108979/47825286-2abb1680-ddc5-11e8-91bf-7e48d4f2dfed.png)

This exists across multiple browsers/refreshes/internet connections/days so is clearly something inside dashboard.

**Comment by jeremyh** [comment]
Thanks for the report Damien! 

Given that it's the most recent month, my suspicion is an off-by-one of the month range (inclusive vs exclusive end?) when generating summaries. 

Day views are generated "live" from the index so will not be affected.

**Comment by jeremyh** [comment]
Hah, I was having trouble reproducing this one. I've finally figured it out: it's because at some point cubedash tables were added to the upstream NCI database.

The summary generator skips products that are already generated (which is usually good! no error produced), and now the database contains stale summaries after cloning from NCI. So it's skipping many of the products.

(the summary process still looked busy at a glance as it was summarising all of the newly-added products. )

Bah 😄

**Comment by jeremyh** [comment]
The cubedash schema is now excluded in the load script, and the months should be correct after last night's update.

I've got a separate task to add a refresh command for existing summaries. Most of the scaffolding to do it is already in place.
