### ISSUE TITLE
Incorrect display of region polygons in date summary

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#484]
While browsing the spatial summary of a [DEA Product](https://explorer.nci.dea.ga.gov.au/products/ga_s2am_ard_3/2022/11/1), there is confusing and wrong display of Dataset regions.

When I mouse over many of the polygons at the above link, Two polygons highlight instead of One, both report the same name and link to the same dataset.

Looking at the source of the GeoJSON, it has lots of Multipolygons instead of simple Polygons. I think each `region_code` should only be a single Polygon.

![2022-11-16_14-28](https://user-images.githubusercontent.com/108979/202077513-01cf139f-4e01-4925-aaa4-bca3617cf8a5.png)

![2022-11-16_14-29](https://user-images.githubusercontent.com/108979/202077521-46c182d3-5767-455f-b7f5-b69dba211b55.png)

Reporting on behalf of Arek.

**Comment by Ariana-B** [comment]
I'm wondering if this is due to some sort of processing issue - the observed behaviour seems to always be caused by a single dataset from late November/early December 2015 having the wrong region code (off by the last letter).

**Comment by JonDHo** [comment]
I have what I suspect is the same issue in our Chile and CEOS instances. What was weird was that it would only happen if I indexed a lot of data at once (e.g. all of continental USA). I have since modified our indexing workflow so that it splits not only on date blocks, but also splits large geographic areas into smaller areas. This has mostly removed the issue, but I could never work out what specifically was causing it. I mostly had the issue with Landsat 8, but I think also with Sentinel-2. The actual bbox in the index database was incorrect as explained below.

This is an example of a bad tile: https://explorer.eail.easi-eo.solutions/products/landsat8_c2l2_sr/datasets/206d355c-8ce8-52a3-b4ef-72e913681684

The geometry and bbox at the STAC endpoint appears to be correct: https://explorer.eail.easi-eo.solutions/stac/collections/landsat8_c2l2_sr/items/f3eaa38d-b383-53e0-8baa-1e3be970c10c

and it has exactly the same geometry and bbox as the original record:
https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr/items/LC08_L2SP_006022_20210802_20210811_02_T1_SR

but the projected geometry shown in the UI is incorrect as is what is stored in the *metadata* column in agdc.dataset as per the screenshot below, so it is an error in the indexing, not in cubedash:
```json
"geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          2994762,
          6953579
        ],
        [
          3066327,
          6755450
        ],
        [
          3258331,
          6823158
        ],
        [
          3184804,
          7024432
        ],
        [
          2994762,
          6953579
        ]
      ]
    ]
  }
```
This puts the tile over near Ireland when it should be on the coast of Quebec.

Just for reference this is a "correct" tile for the same region: https://explorer.eail.easi-eo.solutions/products/landsat8_c2l2_sr/datasets/f3eaa38d-b383-53e0-8baa-1e3be970c10c

And the record directly from agdc.dataset:
![image](https://user-images.githubusercontent.com/3302774/210861254-fcf56ee6-bf42-451e-ab7c-c910cbab50a1.png)

**Comment by dunkgray** [comment]
@omad what is the data field that has 'Multipolygons instead of simple Polygons'? What process is this generated in?
