### ISSUE TITLE
trying to open a link is timing out

### ISSUE THREAD

**Issue by dunkgray** [opendatacube/datacube-explorer#62]
This is an example of a link that's timing out; https://explorer.dea.ga.gov.au/dataset/a066a2ab-42f7-4e72-bc6d-a47a558b8172

It's name is  dsm1sv1_0_Clean_tiff.  So it's probably timing out since it is used to produce so many wofs products.

**Comment by jeremyh** [comment]
Thanks for the report, Duncan.

It's related to #11 as you've guessed, and a rather fun case of it. That one dataset has 2.83 million datasets that derive from it, so it's attempting the load all of them when loading the page.

We'll need to add a 'limit' option to the API so that we can load some sources without loading all of them.

**Comment by dunkgray** [comment]
closed since it's a duplicate of  #11
